### ISSUE TITLE
Code intelligence for Python Can't Find references on Python Flask Repo

### ISSUE THREAD

**Issue by krishnakaranam3732** [sourcegraph/sourcegraph-python#7]
I made sure that I enabled the python extension but I can't find any results on references.

![image](https://user-images.githubusercontent.com/7368391/54009879-6a05c500-4121-11e9-8f3e-5fff22b79971.png)

**Comment by chrismwendt** [comment]
@krishnakaranam3732 Sorry about that, I believe this was a bug in the extension. It should be fixed now :smiley:

**Comment by krishnakaranam3732** [comment]
Awesome! Thanks for the quick fix! :)
